### ISSUE TITLE
Cluster detail access

### ISSUE THREAD

**Issue by tomkukral** [atengler/kqueen-ui#25]
Accessing cluster detail by clicking on small magnifier on the right side of screen is superunconfortable.

Can you make at least cluster name to be a link to cluster detail? The best would be to make all row clickable (except actions row).

![scrot_2017-12-28_073616](https://user-images.githubusercontent.com/6077499/34402467-f2a16ff8-eba1-11e7-8b93-596aea2d0375.png)

**Comment by atengler** [comment]
I made the cluster name clickable. The row itself may be collapsible in the near future, to it shouldn't be used as link to detail.
